package com.anshi.farmproject.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.anshi.farmproject.greendao.UploadLocationEntry;

import com.anshi.farmproject.greendao.UploadLocationEntryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uploadLocationEntryDaoConfig;

    private final UploadLocationEntryDao uploadLocationEntryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uploadLocationEntryDaoConfig = daoConfigMap.get(UploadLocationEntryDao.class).clone();
        uploadLocationEntryDaoConfig.initIdentityScope(type);

        uploadLocationEntryDao = new UploadLocationEntryDao(uploadLocationEntryDaoConfig, this);

        registerDao(UploadLocationEntry.class, uploadLocationEntryDao);
    }
    
    public void clear() {
        uploadLocationEntryDaoConfig.clearIdentityScope();
    }

    public UploadLocationEntryDao getUploadLocationEntryDao() {
        return uploadLocationEntryDao;
    }

}
